name: multi_image_picker
description: Flutter plugin that allows you to display multi image picker on iOS and Android.
version: 4.5.9
author: Radoslav Vitanov <radoslav.vitanov@icloud.com>
homepage: https://github.com/Sh1d0w/multi_image_picker

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.vitanov.multiimagepicker
    pluginClass: MultiImagePickerPlugin
environment:
    sdk: ">=2.0.0-dev.28.0 <3.0.0"
    flutter: ">=1.7.8 <2.0.0"
